### PR TITLE
Correct reduce kwargs

### PR DESCRIPTION
**Pull request by BuZZ-dEE**
rooms_upload sends no message and description, because the dict is
empty after __reduce_kwargs

### CODE REVIEW

**Comment by jadolg** [comment]
this change is breaking the tests for this method exactly. :( are you running the tests before committing?

**Comment by BuZZ-dEE** [comment]
Yes, i saw it. I have a look. It seems that it is a Python 2 vs Python 3 problem.

**Comment by BuZZ-dEE** [comment]
I use also usually Python 3, but I need it also working in Python 2. Maybe there is a solution, that works in both versions.

**Comment by BuZZ-dEE** [comment]
Sorry @jadolg I was a little overhasty last night. ;) The real problem was, that I used the `kwargs` wrong.

Instead of:

```
    def send_log(self, log_file, msg=None, description=None):
        return self.rocket.rooms_upload(
            self._get_room_id(self.config['channel']),
            log_file,
            msg=msg,
            description=description
        )
```

I used wrongly:

```
        response = self.rocket.rooms_upload(
            self._get_room_id(self.config['channel']),
            zipped_log.filename,
            kwargs={
                'msg': msg,
                'description': description
            })
```
I tried the test first after the pull request. So please forgive me. ;)

**Pull request merged**
