### PR TITLE
Livechat - fix tests

### PR DESCRIPTION
**Pull request by dudanogueira**
The previous travis tests were failing over a missing line on end.
Now testing the travis tests in order to advance to full livechat support.

### CODE REVIEW

**Comment by dudanogueira** [comment]
@jadolg, it passed the travis, and now, as expected, it's coverage lowered as I did not wrote the tests yet. But is it a way to go? Looks like everything is working also with the latest version (2.2.0), and the problem is probably some connection rate limit at the rocketchat end, as it spits some timeouts on the docker logs while running tests. thanks!!

**Comment by dudanogueira** [comment]
Rá! https://rocket.chat/docs/developer-guides/rest-api/rate-limiter/
Will give it a try sometime later.

**Comment by jadolg** [comment]
Yes, the rate limiter issue is fixed on the updateto2 branch. Just check the Dockerfile there.
I think you are on the right path :)
Now write some tests so the other checks pass.
I'm currently working on an update to version 2 and have found some problems with certain methods which are timing out on the tests even after removing the rate limiter, so I think it's going to be better for you to use an older version of rocket.chat in the meantime as using the newest version will make almost all the tests fail.

**Comment by dudanogueira** [comment]
Great! Thanks! I will write those tests and finish the remaining livechat methods.
Also, I'll  check this branch for the version 2.

**Comment by jadolg** [comment]
Hey @dudanogueira 
How is this going?
Do you need help?

**Comment by dudanogueira** [comment]
HI, sorry for the late response. I have been playing around with it, but wasn't able to get all the apis endpoints with proper tests.

I got as far as here: https://github.com/dudanogueira/rocketchat_API/tree/livechat

**Comment by jadolg** [comment]
No problem, I just wanted to know cause it's being a while :)
Take your time :) no pressure.

**Pull request closed without merging**
