### PR TITLE
Login with email issue fixed

### PR DESCRIPTION
**Pull request by mayur-rawte**
When you try to login using email it was throwing RocketAuthenticationException

### CODE REVIEW

**Comment by jadolg** [comment]
Hey @mayur-rawte 
Looks like we have some problems in the tests.
Can you fix them?
Thanks for contributing :)

**Comment by jadolg** [comment]
You can check the travis logs here https://travis-ci.org/jadolg/rocketchat_API/jobs/530614303 to see what the problems are

**Comment by mayur-rawte** [comment]
@jadolg fixed CI test issues

**Comment by jadolg** [comment]
@mayur-rawte fantastic!
can you also create a test for it so this way we always know it's always going to be working?
unit tests are really helpful and we value it very much.
thanks a lot again for your time :)
let us put that code coverage up again :clap:

**Comment by mayur-rawte** [comment]
Added Test Case @jadolg

**Comment by jadolg** [comment]
@mayur-rawte perfect!
all checks look fantastic :)
thanks for putting your time and dedication on this project.
I'll merge your changes now.

**Pull request merged**
