### PR TITLE
Add more "teams" endpoints.

### PR DESCRIPTION
**Pull request by fangebee**
Hi, I've implemented the following missing function for managing Rocketchat Teams, I thought I would share this work, even if some endpoints are still missing.

### CODE REVIEW

**Comment by jadolg** [comment]
Hi @fangebee :wave: 
Thank you very much for your contribution.
Would you mind adding tests for these methods and fixing the issues detected by Codacy and Deepsource?

**Comment by s0nders** [comment]
Any chance to have this merged in soon? Would be very helpful for a project im working on, thanks!

**Comment by jadolg** [comment]
> Any chance to have this merged in soon? Would be very helpful for a project im working on, thanks!

This PR is not ready for merging yet. I don't know if @fangebee plans to continue working on it.

**Comment by fangebee** [comment]
I just found how to have docker + pytest working. I'll try to finish this before sunday.

**Comment by fangebee** [comment]
Hi, I finally wrote the missing tests and fixed some issues detected by deepsource.
Can you run CodeCov again? I don't know how to do this by myself.

SonarCloud complains about code duplication, but I think it's ok to duplicate code in automated tests. Correct me if I'm wrong.

**Comment by jadolg** [comment]
The duplication Sonar is complaining about is not on the tests but on the code.
The message `"team_id or team_name required"` repeats for 8 exceptions.
Maybe this could be extracted into a constant.

**Comment by fangebee** [comment]
OK, I found the place to view CodeCov reports: https://app.codecov.io/gh/jadolg/rocketchat_API/pull/192
I'll do the necessary to fix those when I have time this week.

**Comment by dsisysteme** [comment]
Hello,
We are very interested in having these features integrated. Is there any way we can assist with this PR to help it get merged?

**Comment by jadolg** [comment]
Because the long period of inactivity, I think it's safe to assume this PR is not going to get worked on anymore.
Please either open a PR of your own with the changes or create an issue an I'll work on it.

**Comment by dsisysteme** [comment]
We will create an issue because we are not sure we can properly fix the errors raised by the CI/CD. But if this approach doesn't work for you, please let us know—the goal is to get these features implemented as quickly as possible!

**Comment by jadolg** [comment]
Superseeded by https://github.com/jadolg/rocketchat_API/pull/278

**Pull request closed without merging**
