### PR TITLE
Implementation of "chat.sendMessage" API endpoint

### PR DESCRIPTION
**Pull request by JayBraker**
As mentioned in Issue #112 this is my own crude implementation of the endpoint, I tried staying true to the formatting.
Merge or adaptation would be much appreciated.

### CODE REVIEW

**Comment by jadolg** [comment]
Hi :wave: 
Thank you very much for contributing. 
I have a couple of remarks I would like to go around.
1. The method does not really match the signature [here](https://docs.rocket.chat/api/rest-api/methods/chat/sendmessage) so I'm not sure how/why this works
2. Related also to this, we do not know if something works before we test :wink: Would you please add tests for the new method so we can ensure it works and it keeps working even if we decide to refactor everything?

**Comment by JayBraker** [comment]
1: The signature of the endpoint would be required payload arguments?
So to represent the signature better, the method should receive the message dict right away I guess?
This whole thing is new to me :D

2: Will look into that

**Comment by JayBraker** [comment]
I guess it "works" now :D
The tests cover standard "sending message with no text, raising on missing rid" and "sending messag with predefined message._id, deleting that message".
Deleting might be a duplicate as that was already covered by "test_chat_post_update_delete_message".
I didnt cover updating the message for the same reason.
Should I remove the "delete message" for dupe?

**Comment by jadolg** [comment]
Well, that looks good :D
I'll merge it now and release a new version ASAP

**Pull request merged**
