### PR TITLE
Backport to Python 2.7

### PR DESCRIPTION
**Pull request by herronelou**
Reading https://github.com/jadolg/rocketchat_API/issues/3, it looks like at least at one point there was a desire to support python 2.7. 
While it's meant to be dead and buried right now, I've had to add support for it today for usage along with some other libraries and compiled programs that haven't been updated yet.

Seeing as the changes required to make it work in python 2.7 were very minimal, maybe you would like to merge it.
All that was required was replacing the non-ascii apostrophe used in some docstrings with an ascii apostrophe, and replacing a few f-strings with str.format().

### CODE REVIEW

**Review by jadolg — CHANGES_REQUESTED** [review]
Please add python 2.7 back to the tests over here https://github.com/jadolg/rocketchat_API/blob/2061f00b97b94bd47e0bcf35d63ec388e428be04/.github/workflows/build.yml#L17 
and correct the problems found by the CI

**Comment by jadolg** [comment]
I decided to stop supporting 2.7 back when it EoLed but if there's someone using it makes sense.

**Comment by herronelou** [comment]
Hello, thanks for the feedback.
Concerning the issues raised by the CI, one of the issue it complains about is that I'm not using f-strings, which is the point of the change, I'll look into how to disable this warning, 
The others were about lines too long, one of which I've introduced, the others were already here in the docstring, do you want me to reformat the ones for which I only changed the apostrophe?

**Comment by jadolg** [comment]
> Hello, thanks for the feedback. Concerning the issues raised by the CI, one of the issue it complains about is that I'm not using f-strings, which is the point of the change, I'll look into how to disable this warning, The others were about lines too long, one of which I've introduced, the others were already here in the docstring, do you want me to reformat the ones for which I only changed the apostrophe?

Looks like deepsource only gets triggered for changes and it was introduced after we wrote those docstrings. I'll fix that at some point. Don't pay too much attention to deepsource but to the Test and Publish workflow (https://github.com/jadolg/rocketchat_API/runs/7219372176?check_suite_focus=true). Please start by formatting the files you changed with **black**

**Comment by herronelou** [comment]
Hi @jadolg.
Sorry for the delay, I've had other things to deal with at work that took priority over attempting to fix this.

I've enabled the actions on my fork so that I could try to get it passing by adding 2.7 to the test matrix, I've had to do a small tweak to the actions as black doesn't run on 2.7.

However, the tests fail but they also fail using your master at the same stage:
https://github.com/jadolg/rocketchat_API/actions/runs/2598852580

You're likely a lot more familiar with the RocketChat API than I am, maybe you know how to fix this one.

**Comment by jadolg** [comment]
Hi @herronelou 
fantastic! I'm aware of the failure of the tests. We always test against the latest rocket.chat version and looks like they changed something upstream that made this method fail. I already posted about it over here https://open.rocket.chat/channel/python_rocketchat_api but I have not had answers yet.

**Comment by jadolg** [comment]
If you are interested in following up, here's the ticket on rocket.chat. https://github.com/RocketChat/Rocket.Chat/issues/26262

**Comment by jadolg** [comment]
hey @herronelou :wave: 
Would you mind rebasing against `master`?
The issue should be gone already.

**Comment by jadolg** [comment]
I'll be releasing this today

**Comment by herronelou** [comment]
Thanks! Sorry for the delay, I was away at a conference all week.

**Comment by herronelou** [comment]
Thanks for the update :)

**Pull request merged**
