### PR TITLE
set_custom_fields method added

### PR DESCRIPTION
**Pull request by GregorGrasselli**
Added a call to this method:
https://rocket.chat/docs/developer-guides/rest-api/channels/setcustomfields/

### CODE REVIEW

**Comment by jadolg** [comment]
Hi @GregorGrasselli thanks for your contribution! Seems that your commit has not passed the Travis and Codacy checks :'( Can you fix this? It is a PEP8 related issue so it's going to be easy to fix. Also, can you please provide a tests for your new method? We are trying to keep code quality high :-) Thanks again for contributing. Please do this so I'm able to merge.

**Comment by jadolg** [comment]
Awesome! it is looking good already :) now lets create a test so we keep our tests coverage up.

**Comment by jadolg** [comment]
Seems that the test is failing now:
```=================================== FAILURES ===================================
____________________ TestRooms.test_rooms_set_custom_fields ____________________
self = <tests.tests.TestRooms testMethod=test_rooms_set_custom_fields>
    def test_rooms_set_custom_fields(self):
        cf = {'key': 'value'}
>       rooms_set_custom_fields = self.rocket.rooms_set_custom_fields('GENERAL', cf).json()
tests/tests.py:528: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../../virtualenv/python3.6.3/lib/python3.6/site-packages/requests/models.py:892: in json
    return complexjson.loads(self.text, **kwargs)
/opt/python/3.6.3/lib/python3.6/json/__init__.py:354: in loads
    return _default_decoder.decode(s)
/opt/python/3.6.3/lib/python3.6/json/decoder.py:339: in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ```
Can you debug to see what is happening? Have you run the tests in your environment?

**Comment by GregorGrasselli** [comment]
It seems that
```python
self.rocket.rooms_set_custom_fields(...)
```
does not contain json but a blob of html, that is probably an error message of some sort. It works in my environment with rocket.chat version 0.65.1 the `theSetCustomFields` method is quite new and when trying to run it with 0.64.1, I got the same error locally.

**Comment by jadolg** [comment]
All tests are passing now :). Something else before merging:
setCustomFields is a method of "groups" and "channels", but no of "rooms", so according to your implementation it should be called channels_set_custom_fields instead of rooms_set_custom_fields.

**Comment by jadolg** [comment]
Thanks for all your work @GregorGrasselli :) New version is already released!

**Pull request merged**
